/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUS_INTERFACE_H
#define DBUS_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.polkit.qt.example.dbus
 */
class ComPolkitQtExampleDbusInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.polkit.qt.example.dbus"; }

public:
    ComPolkitQtExampleDbusInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComPolkitQtExampleDbusInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> echo()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("echo"), argumentList);
    }

    inline QDBusPendingReply<bool> writeEtc(const QString &text)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(text);
        return asyncCallWithArgumentList(QStringLiteral("writeEtc"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace polkit {
    namespace qt {
      namespace example {
        typedef ::ComPolkitQtExampleDbusInterface dbus;
      }
    }
  }
}
#endif
