/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DbusAdaptor
 */

DbusAdaptor::DbusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

QString DbusAdaptor::echo()
{
    // handle method call com.polkit.qt.example.dbus.echo
    QString out0;
    QMetaObject::invokeMethod(parent(), "echo", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool DbusAdaptor::writeEtc(const QString &text)
{
    // handle method call com.polkit.qt.example.dbus.writeEtc
    bool out0;
    QMetaObject::invokeMethod(parent(), "writeEtc", Q_RETURN_ARG(bool, out0), Q_ARG(QString, text));
    return out0;
}

